feat: update product
ButchLendio/training pull request #11
Opened 2021-07-19 00:58 UTC by Butcher-L

add update product end point

2021-07-19 06:30 UTC, ralphcasipe1 requested changes

2021-07-19 06:30 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +        const updateProduct = await Products.findByIdAndUpdate(id, body)
You can use the `const product` here for example:
```ts
product.update({ new: true })
```

2021-07-19 06:30 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +        let body = ctx.request.body;
I think you can destructure this.

2021-07-19 06:56 UTC, Butcher-L commented on source/controllers/products.ts
> +        const updateProduct = await Products.findByIdAndUpdate(id, body)
i try to use your recommendation sir @ralphcasipe1 but the code says that it is deprecated
![image](https://user-images.githubusercontent.com/85335914/126116156-b5cb1bf1-6247-4559-aa65-b5d69a222339.png)

2021-07-19 09:19 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +        const updateProduct = await Products.findByIdAndUpdate(id, body)
Is it possible to use `updateOne`?

2021-07-20 14:12 UTC, ralphcasipe1 requested changes

2021-07-20 14:12 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +        const result = await Products.findById(id)
is the `__v` field included here?

You can also use the `updateProduct` like this:
```
const updateProduct = await Products.updateOne({ id, body }, { new: true });
```

2021-07-20 14:12 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +        expect(res.status).to.equal(200)
I think you should also check the body.

2021-07-20 14:12 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +        expect(res.status).to.equal(400)
I think you should also check the message.

2021-07-20 14:12 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +        expect(res.status).to.equal(400)
You should also check the message

2021-07-20 23:59 UTC, Butcher-L commented on source/controllers/products.ts
> +        const result = await Products.findById(id)
i try the `Products.update` but it says that update is deprecated

2021-07-21 00:20 UTC, ralphcasipe1 requested changes

2021-07-21 00:20 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +        const result = await Products.findById(id)
Oh you can use the `updateOne` then make sure it has the `{new: true}` option like this:
```ts
    const updateProduct = await Products.updateOne({id, body}, { new: true })
```

so that you don't need to do this inside the `if (updateProduct)`:
```ts
const result = await Products.findById(id)
```

You can instead do this:
```ts
 const updatedProduct = await Products.updateOne({id, body})

    if(updatedProduct){
       ctx.status=200
        ctx.body={updatedProduct}
    } else { ... }
```

2021-07-21 07:57 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +        expect(res.status).to.equal(200)
I think you should assert the `res.body` please

2021-07-21 08:21 UTC, ralphcasipe1 requested changes

2021-07-21 08:21 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +        ctx.body={updateProduct}
change this to: 
```ts
ctx.body = updatedProduct
```

2021-07-21 08:21 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +    const updateProduct = await Products.updateOne({id, body},{new: true})
change this to:
```ts
const updatedProduct = await Products.findByIdAndUpdate({id, body}, { new: true })
```

2021-07-21 08:21 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +    it("Update product - POST/products/:id", async function(){
The description should be:
```ts
it('Update product - PATCH/products/:id')
```

2021-07-21 08:21 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +        expect(res.body.updateProduct.ok).to.equal(1)
Please remove the `res.body.updateProduct.ok`, we don't need to assert this.

Check the `res.body`
```ts
        expect(res.body.product).to.eqls(<updated product>)
```

2021-07-21 08:53 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +        ctx.body={updateProduct}
This is resolved

2021-07-21 08:54 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +    const updateProduct = await Products.updateOne({id, body},{new: true})
Resolved

2021-07-21 08:55 UTC, ralphcasipe1 requested changes

2021-07-21 08:55 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +        expect(res.status).to.equal(200)
Please also check the `res.body.product` if  it's really updated base on your inputs

2021-07-21 08:55 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +    it.only("Update product - PATCH/products/:id", async function(){
Remove `.only`

2021-07-21 08:57 UTC, Butcher-L commented on test/products/products.spec.ts
> +    it.only("Update product - PATCH/products/:id", async function(){
sorry my bad

2021-07-21 09:04 UTC, ralphcasipe1 requested changes

2021-07-21 09:04 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +    it("Not the owner of the product - POST/products/:id", async function(){
Change the description to:
```
DELETE /products/:id
```

2021-07-21 09:04 UTC, ralphcasipe1 commented on test/products/products.spec.ts
> +//     })
Why is this commented out?

2021-07-21 09:15 UTC, ralphcasipe1 approved these changes
LGTM 🎉

2021-07-21 09:15 UTC, merged