feat: add cursor on create
ButchLendio/training pull request #13
Opened 2021-07-20 05:40 UTC by Butcher-L

add cursor on add product

2021-07-20 12:46 UTC, ralphcasipe1 requested changes

2021-07-20 12:46 UTC, ralphcasipe1 commented on source/interfaces/products.ts
> +    cursor: string;
This should be type `Buffer` instead of `string`

2021-07-20 14:53 UTC, ccpacillos requested changes

2021-07-20 14:53 UTC, ccpacillos commented on source/controllers/products.ts
> +    const buffer = Buffer.alloc(8, 0);
I think in the schema of your model, you can do something like this:

```typescript
const ProductSchema = new Schema(
  {
    _id: { type: String, index: true },
    name: { type: String },
    createdAt: { type: Date },
    __cursor: {
      type: Buffer,
      index: true,
      default: function (this: ProductDocument) {
        return Buffer.concat([
          Buffer.from(`${this.createdAt.getTime()}`),
          Buffer.from(this._id),
        ]);
      },
    },
  },
  { timestamps: false }
);
```
This will set the default value for your `__cursor` whenever you call `Product.create()`.

Can validate this one @ralphcasipe1? I may have missed something here, please correct me if there's anything you see wrong. 👍

2021-07-20 15:06 UTC, ccpacillos commented on source/controllers/products.ts
> +    const buffer = Buffer.alloc(8, 0);
Also take note that `default` values are only applied when you create a new document. If you want to use `Product.updatedAt` value for your cursor ordering, then you can just generate the cursor the same way but explicitly specifying it on `.create` and `.updateOne`.

Simplifying the schema:
```typescript
const ProductSchema = new Schema(
  {
    _id: { type: String, index: true },
    name: { type: String },
    createdAt: { type: Date },
    __cursor: {
      type: Buffer,
      index: true,
    },
  },
  { timestamps: false }
);
```

On creating product:
```typescript
const createdAt = new Date();
const cursor = Buffer.concat([
  Buffer.from(`${createdAt.getTime()}`),
  Buffer.from(id),
]);
await Product.create({
  //... other required properties
  __cursor: cursor,
});
```

On updating product:
```typescript
const updatedAt = new Date();
const cursor = Buffer.concat([
  Buffer.from(`${updatedAt.getTime()}`),
  Buffer.from(id),
]);

await Product.updateOne(
  { _id: id },
  { 
    cursor, 
    updatedAt 
  }
);
```

2021-07-21 07:52 UTC, ralphcasipe1 requested changes

2021-07-21 07:52 UTC, ralphcasipe1 commented on source/controllers/products.ts
> +    Buffer.from(id),
No indent here

2021-07-21 07:57 UTC, ralphcasipe1 approved these changes

2021-07-21 08:10 UTC, merged