Feat: add user
ButchLendio/training pull request #4
Opened 2021-07-15 09:34 UTC by Butcher-L

add user end point
add test

2021-07-15 12:37 UTC, ccpacillos requested changes

2021-07-15 12:37 UTC, ccpacillos commented on source/controllers/users.ts
> +    if(!name){
You also need to check whether the input `name` is a string or not.

2021-07-15 12:37 UTC, ccpacillos commented on source/controllers/users.ts
> +        return
The three lines here I think is equivalent to `ctx.throw(400, 'Name required.');`

2021-07-16 02:18 UTC, ralphcasipe1 requested changes

2021-07-16 02:18 UTC, ralphcasipe1 commented on source/test/users/users.spec.ts
> +          };
@ButchLendio  I think you should create a generator for users to be use as mock  in tests, this would reduce repeating same code like this:
```ts
const user = {
  name: internet.userName(),
  username: internet.userName(),
  password: internet.password(),
};
```

2021-07-16 02:31 UTC, Butcher-L commented on source/test/users/users.spec.ts
> +          };
okay @ralphcasipe1 , but sir Clint suggests that  in every it() there should be a different input if I was mistaken

2021-07-16 02:43 UTC, ralphcasipe1 commented on source/test/users/users.spec.ts
> +          };
I mean the generators is using fakerjs

2021-07-16 02:49 UTC, ccpacillos commented on source/test/users/users.spec.ts
> +          };
Add a helper method/function like `generateFakeUser()` or `getRandomUser()` that returns random values of a user object each time it's called.
This will reduce code repetition in your tests.
It will still generate different input values per `it()` so you still maintain isolation per test cases.

What I meant before was to avoid (as much as possible) test cases to share variables that are globally declared outside the test cases.

So the code above can be effectively reduced to:
```typescript
const user = getRandomUser();
```

2021-07-16 03:04 UTC, Butcher-L commented on source/test/users/users.spec.ts
> +          };
copy

2021-07-16 05:35 UTC, ralphcasipe1 commented on test/users/users.spec.ts
> +        console.log(userCreate)
@ButchLendio  Please remove `console.log`

2021-07-16 05:35 UTC, ralphcasipe1 approved these changes

2021-07-16 06:15 UTC, merged