feat: add product
ButchLendio/training pull request #9
Opened 2021-07-16 10:29 UTC by Butcher-L

add product end point
add test

2021-07-17 00:24 UTC, ccpacillos requested changes

2021-07-17 00:24 UTC, ccpacillos commented on source/controllers/products.ts
> +export const addProducts = async(ctx,next) =>{
Rename this to `addProduct`.

2021-07-17 00:24 UTC, ccpacillos commented on source/controllers/products.ts
> +        return
No need to `return` when you use `ctx.throw`.

2021-07-17 00:24 UTC, ccpacillos commented on source/controllers/products.ts
> +    if(typeof price!="number"){
Use double `!==`.

2021-07-17 00:24 UTC, ccpacillos commented on source/controllers/products.ts
> +    const find = await Products.exists({name})
Use a more sensible name than `find`. For example, `productExists`.

2021-07-17 00:24 UTC, ccpacillos commented on source/controllers/products.ts
> +        createdBy:decodedUsername
No need to instantiate it here. This is inefficient since you are instantiating a product even if it's not guaranteed yet to be saved.

2021-07-17 00:24 UTC, ccpacillos commented on source/middlewares/extract-jwt.ts
> +    ctx.throw(400, "Session Expired")
Just throw a generic error message like `"Invalid token."`. We can't be so sure that the error here is due to the token being expired.

2021-07-17 00:24 UTC, ccpacillos commented on source/models/products.ts
>          name: { type: String, require: true },
I think it should be `required`, not `require`.

2021-07-17 00:24 UTC, ccpacillos commented on source/routes/products.ts
> +router.get('/products', getAllProducts);
This PR is only for adding a product. Don't include other code changes not related to that.

2021-07-17 00:24 UTC, ccpacillos commented on source/controllers/products.ts
> +    const find = await Products.exists({name})
Please follow the specs in the exercise. You are missing the `id` input from the user for the product. The `id` is the unique identifier for the product, not the `name`.

2021-07-17 00:24 UTC, ccpacillos commented on test/products/products.spec.ts
> +describe("",()=>{
Missing title for your `describe`.

2021-07-17 00:24 UTC, ccpacillos commented on test/products/products.spec.ts
> +    let token
Why declare this variable outside the test cases? Just declare it within your `it()`.
`const token = ...;`

2021-07-17 00:24 UTC, ccpacillos commented on test/products/products.spec.ts
> +        const res = await Request(Server).post("/products")
Your test cases should be isolated and should not be dependent from one another. Generate a new user specifically for each of your test cases.

2021-07-19 06:15 UTC, ralphcasipe1 approved these changes

2021-07-19 06:15 UTC, merged